import datetime
print("First date")
print("year?")
y=int(input())
print("month?")
m=int(input())
print("day?")
d=int(input())
z=datetime.datetime(y,m,d)
print("Second date")
print("year?")
y=int(input())
print("month?")
m=int(input())
print("day?")
d=int(input())
x1=datetime.datetime(y,m,d)
print("Difference=",(z-x1).total_seconds())